from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
from bs4 import BeautifulSoup
import datetime
from datetime import date
import schedule
import time
import mysql.connector
import OptionChainCalZerodhaFBankNifty
#from OptionChainCalZerodhaF import OptionChainCal
import logging
import requests

#Create and configure #logging
logging.basicConfig(filename="LogFile.log",format='%(asctime)s %(message)s',filemode='w')
#Creating an object
#logging=logging.getlogging(__name__)

data = pd.read_csv('zerodha.txt', header = None)

api_key=data.iloc[0][0]
access_token=data.iloc[0][1]

#con = sqlite3.connect('Momentum.db')
db = mysql.connector.connect(host="localhost",user="username",password="Password",database="DBname")
#con = mydb.cursor()

SQLGetExpirymin='select min(expiry) from InstrumentStatic where name ="BANKNIFTY"'
Expirymin=pd.read_sql(SQLGetExpirymin, db)
Expirymin=str(Expirymin.iloc[0][0])
print(Expirymin)
SQLGetTradingSymbol = 'select tradingsymbol from InstrumentStatic where name ="BANKNIFTY" and expiry ="'+ Expirymin +'"'
#print( SQLGetTradingSymbol )
distinctTradingSymbol = pd.read_sql( SQLGetTradingSymbol, db )

URLforAPI = 'https://api.kite.trade/quote?api_key='+ api_key +'&access_token='+ access_token +'&i=NFO:'
for i in range( distinctTradingSymbol.size ):
    tradingSymbol = distinctTradingSymbol.iloc[i][0]
    URLforAPI = URLforAPI+"&i=NFO:"+ tradingSymbol
print( URLforAPI )

#con.close()

def GetDataNLoadInDatabase():
    
    logging.info("Started at : "+str(datetime.datetime.now() ))
    try:
        #mydb = mysql.connector.connect(host="localhost",user="Prutha",password="Prutha$30",database="Momentum")
        conn = db.cursor()
        print("Started at : "+str(datetime.datetime.now() ))
        loadTime = datetime.datetime.now().time()
        LoadDate = date.today()
        print(LoadDate)
        print(loadTime)

        request = requests.get(url = URLforAPI)
        dajs = request.json()
        

        DataDf = pd.DataFrame.from_dict(dajs["data"], orient='index').T

        tradingSymbollist = pd.DataFrame(DataDf.columns.values)
        print("--------------------------------------BANKNIFTY-----------------------------------------------")
        logging.info("--------------------------------------BANKNIFTY-----------------------------------------------")

        for i in range(tradingSymbollist.size):
            tradingSymbol = tradingSymbollist.iloc[i][0]
            optionType = tradingSymbol[-2:]
            withoutOT = tradingSymbol[:-2]
            StrikePrice = withoutOT[-5:]
            name = tradingSymbol[4:9]
            
            timestamp = str(DataDf[tradingSymbol][1] )          
            last_price = DataDf[tradingSymbol][3]       
            last_quantity = DataDf[tradingSymbol][4]    
            buy_quantity = DataDf[tradingSymbol][5]     
            sell_quantity = DataDf[tradingSymbol][6]    
            volume = DataDf[tradingSymbol][7]          
            average_price = DataDf[tradingSymbol][8]     
            oi = DataDf[tradingSymbol][9]   
            oi_day_high = DataDf[tradingSymbol][10]     
            oi_day_low = DataDf[tradingSymbol][11]    
            OHLC_Open = DataDf[tradingSymbol][15]['open']
            OHLC_High = DataDf[tradingSymbol][15]['high']
            OHLC_Low = DataDf[tradingSymbol][15]['low']
            OHLC_Close = DataDf[tradingSymbol][15]['close']

            #print("('"+str(timestamp)+"','"+str(tradingSymbol)+"',"+str(LoadDate)+",'"+str(loadTime)+"',"+str(oi)+","+str(last_price)+","+str(last_quantity)+","+str(buy_quantity)+","+str(sell_quantity)+","+str(volume)+","+str(average_price)+","+str(oi_day_high)+","+str(oi_day_low)+","+str(OHLC_Open)+","+str(OHLC_High)+","+str(OHLC_Low)+","+str(OHLC_Close)+",'"+str(name)+"',"+str(Expirymin)+","+str(StrikePrice)+",'"+str(optionType)+"')")
            #conn.execute("INSERT INTO OptionChainZerodha(timestamp,TradingSymbol,LoadDate,LoadTime,OI,Last_price,Last_quantity,Buy_quantity,Sell_quantity,Volume,Average_price,OI_day_high,OI_day_low,OHLC_Open,OHLC_High,OHLC_Low,OHLC_Close,Name,Expirty_dt,Strikeprice,OptionType) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",(timestamp,tradingSymbol,str(LoadDate),loadTime,oi,last_price,last_quantity,buy_quantity,sell_quantity,volume,average_price,oi_day_high,oi_day_low,OHLC_Open,OHLC_High,OHLC_Low,OHLC_Close,name,Expirymin,StrikePrice,optionType))
            if(optionType=='PE') or (optionType=='CE'):
                conn.execute("INSERT INTO OptionChainZerodhaBankNifty(timestamp,TradingSymbol,LoadDate,Name,OptionType,LoadTime,OI,Last_price,Last_quantity,Buy_quantity,Sell_quantity,Volume,Average_price,OI_day_high,OI_day_low,OHLC_Open,OHLC_High,OHLC_Low,OHLC_Close,Expirty_dt,Strikeprice) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",(timestamp,tradingSymbol,str(LoadDate),name,optionType,str(loadTime),oi,last_price,last_quantity,buy_quantity,sell_quantity,volume,average_price,oi_day_high,oi_day_low,OHLC_Open,OHLC_High,OHLC_Low,OHLC_Close,Expirymin,StrikePrice))
                db.commit()
        #print("Data Loaded in Database at "+str(LoadDate)+str(loadTime))
        print("Got OptionChain Data from Zerodha and loaded for BANKNIFTY at : "+str(datetime.datetime.now() ))
        print("---------------------------------------BANKNIFTY----------------------------------------------")
        logging.info("Got OptionChain Data from Zerodha and loaded for BANKNIFTY at : "+str(datetime.datetime.now() ))
        logging.info("--------------------------------------BANKNIFTY-----------------------------------------------")
        conn.close()
        print("goining in calculation ")
        logging.info("goining in calculation")

        OptionChainCalZerodhaFBankNifty.OptionChainCal()
        print("Backin OptionChain BANKNIFTY")
        logging.info("Backin OptionChain BANKNIFTY")
    except Exception as e: 
        print(str(e))
        print("Error occured")
        pass

#GetDataNLoadInDatabase()
try:
    schedule.every().monday.at('09:19').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('09:22').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('09:25').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('09:28').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('09:31').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('09:34').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('09:37').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('09:40').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('09:43').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('09:46').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('09:49').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('09:52').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('09:55').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('09:58').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:01').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:04').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:07').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:10').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:13').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:16').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:19').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:22').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:25').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:28').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:31').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:34').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:37').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:40').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:43').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:46').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:49').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:52').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:55').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('10:58').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:01').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:04').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:07').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:10').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:13').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:16').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:19').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:22').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:25').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:28').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:31').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:34').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:37').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:40').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:43').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:46').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:49').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:52').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:55').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('11:58').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:01').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:04').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:07').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:10').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:13').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:16').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:19').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:22').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:25').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:28').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:31').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:34').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:37').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:40').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:43').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:46').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:49').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:52').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:55').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('12:58').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:01').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:04').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:07').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:10').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:13').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:16').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:19').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:22').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:25').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:28').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:31').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:34').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:37').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:40').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:43').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:46').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:49').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:52').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:55').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('13:58').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:01').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:04').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:07').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:10').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:13').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:16').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:19').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:22').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:25').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:28').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:31').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:34').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:37').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:40').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:43').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:46').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:49').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:52').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:55').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('14:58').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('15:01').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('15:04').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('15:07').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('15:10').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('15:13').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('15:16').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('15:19').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('15:22').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('15:25').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('15:28').do(GetDataNLoadInDatabase)
    schedule.every().monday.at('15:31').do(GetDataNLoadInDatabase)

    schedule.every().tuesday.at('09:19').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('09:22').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('09:25').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('09:28').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('09:31').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('09:34').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('09:37').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('09:40').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('09:43').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('09:46').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('09:49').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('09:52').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('09:55').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('09:58').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:01').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:04').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:07').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:10').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:13').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:16').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:19').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:22').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:25').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:28').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:31').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:34').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:37').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:40').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:43').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:46').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:49').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:52').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:55').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('10:58').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:01').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:04').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:07').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:10').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:13').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:16').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:19').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:22').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:25').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:28').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:31').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:34').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:37').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:40').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:43').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:46').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:49').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:52').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:55').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('11:58').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:01').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:04').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:07').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:10').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:13').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:16').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:19').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:22').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:25').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:28').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:31').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:34').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:37').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:40').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:43').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:46').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:49').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:52').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:55').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('12:58').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:01').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:04').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:07').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:10').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:13').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:16').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:19').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:22').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:25').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:28').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:31').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:34').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:37').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:40').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:43').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:46').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:49').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:52').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:55').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('13:58').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:01').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:04').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:07').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:10').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:13').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:16').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:19').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:22').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:25').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:28').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:31').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:34').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:37').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:40').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:43').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:46').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:49').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:52').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:55').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('14:58').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('15:01').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('15:04').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('15:07').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('15:10').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('15:13').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('15:16').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('15:19').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('15:22').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('15:25').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('15:28').do(GetDataNLoadInDatabase)
    schedule.every().tuesday.at('15:31').do(GetDataNLoadInDatabase)

    schedule.every().wednesday.at('09:19').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('09:22').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('09:25').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('09:28').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('09:31').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('09:34').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('09:37').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('09:40').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('09:43').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('09:46').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('09:49').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('09:52').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('09:55').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('09:58').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:01').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:04').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:07').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:10').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:13').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:16').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:19').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:22').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:25').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:28').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:31').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:34').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:37').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:40').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:43').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:46').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:49').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:52').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:55').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('10:58').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:01').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:04').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:07').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:10').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:13').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:16').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:19').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:22').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:25').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:28').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:31').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:34').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:37').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:40').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:43').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:46').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:49').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:52').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:55').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('11:58').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:01').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:04').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:07').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:10').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:13').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:16').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:19').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:22').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:25').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:28').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:31').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:34').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:37').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:40').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:43').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:46').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:49').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:52').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:55').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('12:58').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:01').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:04').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:07').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:10').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:13').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:16').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:19').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:22').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:25').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:28').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:31').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:34').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:37').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:40').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:43').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:46').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:49').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:52').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:55').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('13:58').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:01').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:04').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:07').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:10').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:13').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:16').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:19').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:22').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:25').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:28').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:31').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:34').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:37').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:40').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:43').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:46').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:49').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:52').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:55').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('14:58').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('15:01').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('15:04').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('15:07').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('15:10').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('15:13').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('15:16').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('15:19').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('15:22').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('15:25').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('15:28').do(GetDataNLoadInDatabase)
    schedule.every().wednesday.at('15:31').do(GetDataNLoadInDatabase)

    schedule.every().thursday.at('09:19').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('09:22').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('09:25').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('09:28').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('09:31').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('09:34').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('09:37').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('09:40').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('09:43').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('09:46').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('09:49').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('09:52').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('09:55').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('09:58').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:01').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:04').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:07').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:10').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:13').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:16').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:19').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:22').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:25').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:28').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:31').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:34').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:37').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:40').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:43').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:46').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:49').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:52').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:55').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('10:58').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:01').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:04').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:07').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:10').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:13').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:16').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:19').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:22').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:25').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:28').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:31').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:34').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:37').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:40').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:43').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:46').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:49').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:52').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:55').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('11:58').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:01').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:04').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:07').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:10').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:13').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:16').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:19').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:22').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:25').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:28').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:31').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:34').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:37').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:40').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:43').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:46').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:49').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:52').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:55').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('12:58').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:01').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:04').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:07').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:10').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:13').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:16').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:19').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:22').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:25').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:28').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:31').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:34').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:37').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:40').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:43').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:46').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:49').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:52').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:55').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('13:58').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:01').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:04').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:07').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:10').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:13').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:16').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:19').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:22').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:25').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:28').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:31').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:34').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:37').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:40').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:43').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:46').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:49').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:52').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:55').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('14:58').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('15:01').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('15:04').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('15:07').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('15:10').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('15:13').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('15:16').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('15:19').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('15:22').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('15:25').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('15:28').do(GetDataNLoadInDatabase)
    schedule.every().thursday.at('15:31').do(GetDataNLoadInDatabase)

    schedule.every().friday.at('09:19').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('09:22').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('09:25').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('09:28').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('09:31').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('09:34').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('09:37').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('09:40').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('09:43').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('09:46').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('09:49').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('09:52').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('09:55').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('09:58').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:01').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:04').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:07').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:10').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:13').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:16').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:19').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:22').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:25').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:28').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:31').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:34').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:37').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:40').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:43').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:46').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:49').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:52').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:55').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('10:58').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:01').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:04').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:07').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:10').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:13').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:16').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:19').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:22').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:25').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:28').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:31').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:34').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:37').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:40').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:43').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:46').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:49').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:52').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:55').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('11:58').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:01').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:04').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:07').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:10').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:13').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:16').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:19').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:22').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:25').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:28').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:31').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:34').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:37').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:40').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:43').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:46').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:49').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:52').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:55').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('12:58').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:01').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:04').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:07').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:10').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:13').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:16').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:19').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:22').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:25').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:28').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:31').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:34').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:37').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:40').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:43').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:46').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:49').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:52').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:55').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('13:58').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:01').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:04').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:07').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:10').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:13').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:16').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:19').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:22').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:25').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:28').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:31').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:34').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:37').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:40').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:43').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:46').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:49').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:52').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:55').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('14:58').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('15:01').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('15:04').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('15:07').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('15:10').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('15:13').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('15:16').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('15:19').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('15:22').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('15:25').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('15:28').do(GetDataNLoadInDatabase)
    schedule.every().friday.at('15:31').do(GetDataNLoadInDatabase)

except:
    pass

finally:
    print("Finally executed at :"+str(datetime.datetime.now() ))

while True:
    schedule.run_pending()
    time.sleep(1)
